### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by SagePtr** [SagePtr/openserver-apache-2.4#1]
- [x] Add Apache
- [x] Add OpenServer-specific files for Apache (e.g. Certificate Generator bat, etc.)
- [x] Add missing Apache modules from Apache Lounge
- [x] Add missing Apache modules from elsewhere (old Apache in OpenServer if compatible)
- [x] Add Apache+Nginx OpenServer module
- [x] Make release on GitHub when made
- [ ] Write Readme

**Comment by Husniddinuz** [comment]
MaxSecure Trojan.Malware.300983.susgen

I have no idea why your repository showing it contains virus

**Comment by SagePtr** [comment]
> MaxSecure Trojan.Malware.300983.susgen

It's very common practice when 1-2 of 70 antiviruses on Virustotal false-positive report something.
The files in this repo are originally gathered from ApacheLounge (Apache itself + mods), so I doubt there is anything harmful here.
If you have real evidence of harmful file rather than shady heuristic false-positive report, post the evidences and I'll replace or remove the infected files from this bundle.
Also, this bundle contains HTTP-server, but HTTP servers could be potentially risky if misconfigured, so it's even okay for them to be detected by antiviruses.
